import {
  createContext,
  useContext,
  useState,
  useCallback,
  useMemo,
} from "react";

const translations = {
  en: {
    common: {
      home: "Home",
      profile: "Profile",
      dashboard: "Dashboard",
      logout: "Logout",
      save: "Save",
      cancel: "Cancel",
      close: "Close",
      search: "Search",
      loading: "Loading...",
      student: "Student",
      everyone: "Everyone",
      or: "or",
    },
    login: {
      welcome: "Welcome to Mediverse",
      subtitle: "Your AI-Powered Health Companion",
      selectRole: "Choose how you want to experience Mediverse",
      student: "Student",
      everyone: "Everyone",
      forStudents: "For Students",
      forEveryone: "For Everyone",
      studentDesc:
        "Learn medical device usage with AI-guided training, interactive 3D models, and AR simulations.",
      everyoneDesc:
        "Scan devices, understand health readings, get AI guidance, find hospitals, and access emergency help.",
      getStarted: "Get Started",
      emergencyNote: "In case of medical emergency, always dial",
      studentFeature1: "Interactive 3D Medical Training",
      studentFeature2: "Step-by-step Device Guidance",
      studentFeature3: "Practice with AR Simulations",
      studentFeature4: "Track Your Learning Progress",
      everyoneFeature1: "Scan and Identify Medical Devices",
      everyoneFeature2: "Understand Your Health Readings",
      everyoneFeature3: "Find Nearby Hospitals Instantly",
      everyoneFeature4: "One-Click Emergency Assistance",
    },
    arScan: {
      medicalTraining: "Medical Training",
      healthCompanion: "Mediverse",
      studentTitle: "Medical Device Trainer",
      civilianTitle: "Scan Medical Device",
      studentDesc:
        "Learn how to use medical devices with interactive 3D models and step-by-step guidance",
      civilianDesc:
        "Scan your medical device for instant guidance on how to use it properly",
      scanDevice: "Scan Device",
      quickAccess: "Quick Access Devices",
      learnDevices: "Learn Medical Devices",
      allDevices: "All Devices",
      cardiovascular: "Cardiovascular",
      endocrine: "Endocrine",
      respiratory: "Respiratory",
      searchPlaceholder: "Search devices (e.g., blood pressure, glucose...)",
      learn: "Learn",
      viewGuide: "View Guide",
      audio: "Audio",
      noResults: "No devices found for",
      clearSearch: "Clear Search",
      back: "Back",
      previous: "Previous",
      next: "Next",
      complete: "Complete",
      replayAudio: "Replay Audio",
      about: "About",
      usage: "Usage",
      measures: "Measures",
      dragToRotate: "Drag to rotate / Scroll to zoom",
      step: "Step",
      loading3D: "Loading 3D Model...",
      preparing: "Preparing your training environment...",
      audioLanguage: "Audio Language",
    },
    manualInput: {
      title: "Enter Health Reading",
      enterReading: "Enter Reading",
      selectDevice: "Select Device",
      bpMonitor: "Blood Pressure",
      glucometer: "Glucometer",
      thermometer: "Thermometer",
      oximeter: "Oximeter",
      systolic: "Systolic (mmHg)",
      diastolic: "Diastolic (mmHg)",
      pulse: "Pulse (bpm)",
      glucose: "Blood Glucose (mg/dL)",
      temperature: "Temperature (F)",
      spo2: "SpO2 (%)",
      optional: "Optional",
      analyze: "Analyze Reading",
      enterValidReading: "Please enter valid readings",
    },
    analysis: {
      title: "Analysis Result",
      yourReading: "Your Reading",
      findHospital: "Find Nearby Hospital",
      speakResult: "Speak Result",
      bpNormal: "Blood pressure is normal",
      bpNormalRec: "Maintain healthy lifestyle. Continue regular monitoring.",
      bpElevated: "Blood pressure is slightly elevated",
      bpElevatedRec: "Reduce salt intake, exercise regularly, manage stress.",
      bpLow: "Blood pressure is low (Hypotension)",
      bpLowRec:
        "Increase fluid intake, rest, and monitor. Consult doctor if symptoms persist.",
      bpRisk: "Blood pressure indicates Stage 1 Hypertension",
      bpRiskRec: "Consult a doctor. Lifestyle changes recommended.",
      bpHighRisk: "Blood pressure indicates Stage 2 Hypertension",
      bpHighRiskRec: "Seek medical attention soon. Medication may be needed.",
      bpEmergency: "Hypertensive Crisis! Immediate medical attention required!",
      bpEmergencyRec:
        "Call emergency services immediately or go to nearest hospital.",
      glucoseNormal: "Blood glucose is normal (Fasting)",
      glucoseNormalRec: "Maintain balanced diet. Continue regular monitoring.",
      glucoseLow: "Severe Hypoglycemia! Blood sugar is dangerously low!",
      glucoseLowRec:
        "Consume fast-acting sugar immediately. Seek emergency help if unresponsive.",
      glucosePrediabetes: "Prediabetes range (Fasting)",
      glucosePrediabetesRec:
        "Reduce sugar intake, exercise more. Consult doctor.",
      glucoseDiabetes: "Diabetes range - High blood sugar",
      glucoseDiabetesRec: "Consult endocrinologist. Medication may be needed.",
      glucoseVeryHigh: "Very high blood sugar",
      glucoseVeryHighRec: "Seek medical attention. Monitor for ketones.",
      glucoseEmergency: "Diabetic Emergency! Blood sugar critically high!",
      glucoseEmergencyRec:
        "Go to emergency room immediately. Risk of diabetic coma.",
      tempNormal: "Normal body temperature",
      tempNormalRec: "Temperature is healthy. No action needed.",
      tempLow: "Below normal body temperature",
      tempLowRec: "Warm up, rest, and monitor. Consult doctor if persistent.",
      tempSlightFever: "Slight elevation in temperature",
      tempSlightFeverRec: "Rest and stay hydrated. Monitor for changes.",
      tempFever: "Fever detected",
      tempFeverRec:
        "Take fever reducers, rest, stay hydrated. See doctor if persists.",
      tempHypothermia: "Hypothermia! Body temperature is dangerously low!",
      tempHypothermiaRec: "Warm up gradually. Seek emergency care immediately.",
      tempEmergency: "High Fever Emergency! Temperature is dangerously high!",
      tempEmergencyRec:
        "Seek emergency care immediately. Cool down with lukewarm water.",
      oxygenNormal: "Blood oxygen level is normal",
      oxygenNormalRec:
        "Oxygen saturation is healthy. Continue normal activities.",
      oxygenBorderline: "Blood oxygen is slightly below optimal",
      oxygenBorderlineRec: "Practice deep breathing. Monitor closely.",
      oxygenLow: "Low blood oxygen level",
      oxygenLowRec:
        "Seek medical attention. Supplemental oxygen may be needed.",
      oxygenEmergency: "Severe Hypoxemia! Oxygen level is critically low!",
      oxygenEmergencyRec:
        "Call emergency services immediately! Life-threatening condition.",
    },
    categories: {
      normal: "Normal",
      elevated: "Elevated",
      risk: "Risk",
      highRisk: "High Risk",
      emergency: "Emergency",
    },
    emergency: {
      title: "Emergency Assistance",
      emergency: "Emergency",
      criticalReading: "Critical reading detected on",
      specialistNeeded: "Specialist needed",
      findingHospitals: "Finding nearby hospitals...",
      yourLocation: "Your Location",
      call: "Call",
      directions: "Directions",
      ambulanceAvailable: "Ambulance Available",
      confirmCall: "Confirm Emergency Call",
      callQuestion: "Call",
      callNow: "Call Now",
      call108: "Call 108 (Ambulance)",
      call102: "Call 102 (Emergency)",
      activated: "Emergency mode activated. Finding nearest hospitals.",
      locationError: "Unable to get location. Please enable location services.",
    },
    hospitalFinder: {
      title: "Nearby Hospitals",
      findHospital: "Find Hospital",
    },
    contact: {
      title: "Contact Us",
      subtitle: "We are here to help you with your health journey",
      getInTouch: "Get in Touch",
      email: "Email",
      phone: "Phone",
      workingHours: "Working Hours",
      workingHoursValue: "Mon - Sat: 9:00 AM - 6:00 PM",
      sendMessage: "Send Message",
      yourName: "Your Name",
      yourEmail: "Your Email",
      subject: "Subject",
      message: "Message",
      send: "Send Message",
      emergencyNote:
        "For medical emergencies, please call 108 or 102 immediately.",
      followUs: "Follow Us",
    },
  },
  hi: {
    common: {
      home: "होम",
      profile: "प्रोफ़ाइल",
      dashboard: "डैशबोर्ड",
      logout: "लॉग आउट",
      save: "सहेजें",
      cancel: "रद्द करें",
      close: "बंद करें",
      search: "खोजें",
      loading: "लोड हो रहा है...",
      student: "छात्र",
      everyone: "सभी के लिए",
      or: "या",
    },
    login: {
      welcome: "Mediverse में आपका स्वागत है",
      subtitle: "आपका AI-संचालित स्वास्थ्य सहायक",
      selectRole: "अपनी भूमिका चुनें",
      student: "छात्र",
      everyone: "सभी के लिए",
      forStudents: "छात्रों के लिए",
      forEveryone: "सभी के लिए",
      studentDesc:
        "AI-निर्देशित प्रशिक्षण और 3D मॉडल के साथ चिकित्सा उपकरण का उपयोग सीखें।",
      everyoneDesc:
        "उपकरण स्कैन करें, रीडिंग समझें, AI मार्गदर्शन और आपातकालीन सहायता प्राप्त करें।",
      getStarted: "शुरू करें",
      emergencyNote: "चिकित्सा आपातकाल में, हमेशा डायल करें",
      studentFeature1: "इंटरैक्टिव 3D मेडिकल ट्रेनिंग",
      studentFeature2: "चरण-दर-चरण उपकरण मार्गदर्शन",
      studentFeature3: "AR सिमुलेशन के साथ अभ्यास",
      studentFeature4: "अपनी प्रगति ट्रैक करें",
      everyoneFeature1: "चिकित्सा उपकरण स्कैन करें",
      everyoneFeature2: "अपनी स्वास्थ्य रीडिंग समझें",
      everyoneFeature3: "नजदीकी अस्पताल खोजें",
      everyoneFeature4: "एक-क्लिक आपातकालीन सहायता",
    },
    arScan: {
      medicalTraining: "चिकित्सा प्रशिक्षण",
      healthCompanion: "स्वास्थ्य सहायक",
      studentTitle: "चिकित्सा उपकरण प्रशिक्षक",
      civilianTitle: "चिकित्सा उपकरण स्कैन करें",
      studentDesc:
        "इंटरैक्टिव 3D मॉडल और मार्गदर्शन के साथ उपकरणों का उपयोग सीखें",
      civilianDesc: "तुरंत मार्गदर्शन के लिए अपना उपकरण स्कैन करें",
      scanDevice: "उपकरण स्कैन करें",
      quickAccess: "त्वरित पहुंच उपकरण",
      learnDevices: "चिकित्सा उपकरण सीखें",
      allDevices: "सभी उपकरण",
      cardiovascular: "हृदय संबंधी",
      endocrine: "अंतःस्रावी",
      respiratory: "श्वसन",
      searchPlaceholder: "उपकरण खोजें...",
      learn: "सीखें",
      viewGuide: "गाइड देखें",
      audio: "ऑडियो",
      noResults: "कोई परिणाम नहीं",
      clearSearch: "साफ़ करें",
      back: "वापस",
      previous: "पिछला",
      next: "अगला",
      complete: "पूर्ण",
      replayAudio: "ऑडियो दोहराएं",
      about: "जानकारी",
      usage: "उपयोग",
      measures: "माप",
      dragToRotate: "घुमाने के लिए खींचें / ज़ूम के लिए स्क्रॉल करें",
      step: "चरण",
      loading3D: "3D मॉडल लोड हो रहा है...",
      preparing: "आपका प्रशिक्षण वातावरण तैयार हो रहा है...",
      audioLanguage: "ऑडियो भाषा",
    },
    manualInput: {
      title: "स्वास्थ्य रीडिंग दर्ज करें",
      enterReading: "रीडिंग दर्ज करें",
      selectDevice: "उपकरण चुनें",
      bpMonitor: "रक्तचाप",
      glucometer: "ग्लूकोमीटर",
      thermometer: "थर्मामीटर",
      oximeter: "ऑक्सीमीटर",
      systolic: "सिस्टोलिक (mmHg)",
      diastolic: "डायस्टोलिक (mmHg)",
      pulse: "पल्स (bpm)",
      glucose: "रक्त शर्करा (mg/dL)",
      temperature: "तापमान (F)",
      spo2: "SpO2 (%)",
      optional: "वैकल्पिक",
      analyze: "विश्लेषण करें",
      enterValidReading: "कृपया वैध रीडिंग दर्ज करें",
    },
    analysis: {
      title: "विश्लेषण परिणाम",
      yourReading: "आपकी रीडिंग",
      findHospital: "नजदीकी अस्पताल खोजें",
      speakResult: "परिणाम बोलें",
      bpNormal: "रक्तचाप सामान्य है",
      bpNormalRec: "स्वस्थ जीवनशैली बनाए रखें।",
      bpElevated: "रक्तचाप थोड़ा बढ़ा हुआ है",
      bpElevatedRec: "नमक कम करें, नियमित व्यायाम करें।",
      bpLow: "रक्तचाप कम है",
      bpLowRec: "तरल पदार्थ बढ़ाएं, आराम करें।",
      bpRisk: "उच्च रक्तचाप चरण 1",
      bpRiskRec: "डॉक्टर से परामर्श लें।",
      bpHighRisk: "उच्च रक्तचाप चरण 2",
      bpHighRiskRec: "जल्द चिकित्सा सहायता लें।",
      bpEmergency: "आपातकालीन! तुरंत चिकित्सा सहायता लें!",
      bpEmergencyRec: "तुरंत आपातकालीन सेवाओं को कॉल करें।",
      glucoseNormal: "रक्त शर्करा सामान्य है",
      glucoseNormalRec: "संतुलित आहार बनाए रखें।",
      glucoseLow: "रक्त शर्करा खतरनाक रूप से कम है!",
      glucoseLowRec: "तुरंत शर्करा लें।",
      tempNormal: "शरीर का तापमान सामान्य है",
      tempNormalRec: "कोई कार्रवाई की आवश्यकता नहीं।",
      oxygenNormal: "ऑक्सीजन स्तर सामान्य है",
      oxygenNormalRec: "सामान्य गतिविधियां जारी रखें।",
    },
    categories: {
      normal: "सामान्य",
      elevated: "थोड़ा बढ़ा",
      risk: "जोखिम",
      highRisk: "उच्च जोखिम",
      emergency: "आपातकालीन",
    },
    emergency: {
      title: "आपातकालीन सहायता",
      emergency: "आपातकालीन",
      criticalReading: "गंभीर रीडिंग:",
      specialistNeeded: "विशेषज्ञ की आवश्यकता",
      findingHospitals: "नजदीकी अस्पताल खोज रहे हैं...",
      yourLocation: "आपका स्थान",
      call: "कॉल करें",
      directions: "दिशा",
      ambulanceAvailable: "एम्बुलेंस उपलब्ध",
      confirmCall: "कॉल की पुष्टि करें",
      callQuestion: "कॉल करें",
      callNow: "अभी कॉल करें",
      call108: "108 कॉल करें (एम्बुलेंस)",
      call102: "102 कॉल करें (आपातकालीन)",
      activated: "आपातकालीन मोड सक्रिय। अस्पताल खोज रहे हैं।",
      locationError: "स्थान प्राप्त करने में असमर्थ।",
    },
    hospitalFinder: {
      title: "नजदीकी अस्पताल",
      findHospital: "अस्पताल खोजें",
    },
    contact: {
      title: "संपर्क करें",
      subtitle: "हम आपकी स्वास्थ्य यात्रा में मदद के लिए यहां हैं",
      getInTouch: "संपर्क में रहें",
      email: "ईमेल",
      phone: "फोन",
      workingHours: "कार्य समय",
      workingHoursValue: "सोम - शनि: सुबह 9:00 - शाम 6:00",
      sendMessage: "संदेश भेजें",
      yourName: "आपका नाम",
      yourEmail: "आपका ईमेल",
      subject: "विषय",
      message: "संदेश",
      send: "भेजें",
      emergencyNote:
        "चिकित्सा आपातकाल के लिए, कृपया तुरंत 108 या 102 पर कॉल करें।",
      followUs: "हमें फॉलो करें",
    },
  },
  mr: {
    common: {
      home: "होम",
      profile: "प्रोफाइल",
      student: "विद्यार्थी",
      everyone: "सर्वांसाठी",
      cancel: "रद्द करा",
      close: "बंद करा",
      or: "किंवा",
    },
    login: {
      welcome: "Mediverse मध्ये स्वागत",
      subtitle: "तुमचा AI आरोग्य सहाय्यक",
      selectRole: "भूमिका निवडा",
      student: "विद्यार्थी",
      everyone: "सर्वांसाठी",
      forStudents: "विद्यार्थ्यांसाठी",
      forEveryone: "सर्वांसाठी",
      getStarted: "सुरू करा",
      emergencyNote: "आणीबाणीत डायल करा",
      studentFeature1: "3D वैद्यकीय प्रशिक्षण",
      studentFeature2: "चरण-दर-चरण मार्गदर्शन",
      studentFeature3: "AR सिम्युलेशन",
      studentFeature4: "प्रगती ट्रॅक करा",
      everyoneFeature1: "उपकरणे स्कॅन करा",
      everyoneFeature2: "वाचन समजून घ्या",
      everyoneFeature3: "हॉस्पिटल शोधा",
      everyoneFeature4: "आपत्कालीन सहाय्य",
    },
    arScan: {
      medicalTraining: "वैद्यकीय प्रशिक्षण",
      healthCompanion: "आरोग्य सहाय्यक",
      studentTitle: "वैद्यकीय उपकरण प्रशिक्षक",
      civilianTitle: "उपकरण स्कॅन करा",
      scanDevice: "उपकरण स्कॅन करा",
      quickAccess: "जलद प्रवेश",
      learnDevices: "उपकरणे शिका",
      allDevices: "सर्व उपकरणे",
      learn: "शिका",
      viewGuide: "मार्गदर्शक पहा",
      audio: "ऑडिओ",
      back: "मागे",
      previous: "मागील",
      next: "पुढील",
      complete: "पूर्ण",
      replayAudio: "ऑडिओ पुन्हा",
      audioLanguage: "ऑडिओ भाषा",
    },
    manualInput: {
      title: "वाचन प्रविष्ट करा",
      enterReading: "वाचन प्रविष्ट करा",
      selectDevice: "उपकरण निवडा",
      bpMonitor: "रक्तदाब",
      glucometer: "ग्लुकोमीटर",
      thermometer: "थर्मामीटर",
      oximeter: "ऑक्सिमीटर",
      analyze: "विश्लेषण करा",
      enterValidReading: "वैध वाचन प्रविष्ट करा",
    },
    categories: {
      normal: "सामान्य",
      elevated: "वाढलेले",
      risk: "धोक्यात",
      highRisk: "उच्च धोका",
      emergency: "आपत्कालीन",
    },
    emergency: {
      title: "आपत्कालीन सहाय्य",
      emergency: "आपत्कालीन",
      findingHospitals: "हॉस्पिटल शोधत आहे...",
      call: "कॉल करा",
      directions: "दिशा",
      callNow: "आता कॉल करा",
      call108: "108 कॉल करा",
      call102: "102 कॉल करा",
    },
    hospitalFinder: { title: "जवळचे हॉस्पिटल", findHospital: "हॉस्पिटल शोधा" },
    contact: {
      title: "संपर्क साधा",
      subtitle: "आम्ही मदतीसाठी येथे आहोत",
      email: "ईमेल",
      phone: "फोन",
      send: "पाठवा",
      emergencyNote: "आणीबाणीसाठी 108 किंवा 102 वर कॉल करा",
    },
  },
  ta: {
    common: {
      home: "முகப்பு",
      profile: "சுயவிவரம்",
      student: "மாணவர்",
      everyone: "அனைவருக்கும்",
      cancel: "ரத்து",
      close: "மூடு",
      or: "அல்லது",
    },
    login: {
      welcome: "Mediverse-க்கு வரவேற்கிறோம்",
      subtitle: "AI சுகாதார துணை",
      selectRole: "பங்கைத் தேர்ந்தெடுக்கவும்",
      student: "மாணவர்",
      everyone: "அனைவருக்கும்",
      forStudents: "மாணவர்களுக்கு",
      forEveryone: "அனைவருக்கும்",
      getStarted: "தொடங்கு",
      emergencyNote: "அவசரத்தில் டயல் செய்யுங்கள்",
      studentFeature1: "3D மருத்துவ பயிற்சி",
      studentFeature2: "படிப்படியான வழிகாட்டுதல்",
      studentFeature3: "AR உருவகம்",
      studentFeature4: "முன்னேற்றம் கண்காணிக்கவும்",
      everyoneFeature1: "சாதனங்களை ஸ்கேன் செய்யுங்கள்",
      everyoneFeature2: "வாசிப்புகளைப் புரிந்துகொள்ளுங்கள்",
      everyoneFeature3: "மருத்துவமனைகளைக் கண்டறியுங்கள்",
      everyoneFeature4: "அவசர உதவி",
    },
    arScan: {
      medicalTraining: "மருத்துவ பயிற்சி",
      healthCompanion: "சுகாதார துணை",
      studentTitle: "சாதன பயிற்சியாளர்",
      civilianTitle: "சாதனத்தை ஸ்கேன் செய்",
      scanDevice: "சாதனத்தை ஸ்கேன் செய்",
      quickAccess: "விரைவு அணுகல்",
      learnDevices: "சாதனங்களைக் கற்றுக்கொள்",
      allDevices: "அனைத்து சாதனங்கள்",
      learn: "கற்றுக்கொள்",
      viewGuide: "வழிகாட்டி",
      audio: "ஆடியோ",
      back: "பின்",
      previous: "முந்தைய",
      next: "அடுத்து",
      complete: "முடிந்தது",
      replayAudio: "ஆடியோ மீண்டும்",
      audioLanguage: "ஆடியோ மொழி",
    },
    manualInput: {
      title: "வாசிப்பை உள்ளிடுக",
      enterReading: "வாசிப்பை உள்ளிடு",
      selectDevice: "சாதனத்தைத் தேர்ந்தெடு",
      bpMonitor: "இரத்த அழுத்தம்",
      glucometer: "குளுக்கோமீட்டர்",
      thermometer: "வெப்பமானி",
      oximeter: "ஆக்சிமீட்டர்",
      analyze: "பகுப்பாய்வு",
      enterValidReading: "சரியான வாசிப்பை உள்ளிடவும்",
    },
    categories: {
      normal: "இயல்பான",
      elevated: "உயர்ந்த",
      risk: "ஆபத்து",
      highRisk: "அதிக ஆபத்து",
      emergency: "அவசரநிலை",
    },
    emergency: {
      title: "அவசர உதவி",
      emergency: "அவசரநிலை",
      findingHospitals: "மருத்துவமனைகளைக் கண்டறிகிறது...",
      call: "அழைப்பு",
      directions: "திசைகள்",
      callNow: "இப்போது அழைக்கவும்",
      call108: "108 அழைக்கவும்",
      call102: "102 அழைக்கவும்",
    },
    hospitalFinder: {
      title: "அருகிலுள்ள மருத்துவமனைகள்",
      findHospital: "மருத்துவமனையைக் கண்டறி",
    },
    contact: {
      title: "தொடர்பு கொள்ளுங்கள்",
      subtitle: "உதவ நாங்கள் இருக்கிறோம்",
      email: "மின்னஞ்சல்",
      phone: "தொலைபேசி",
      send: "அனுப்பு",
      emergencyNote: "அவசரநிலைக்கு 108 அல்லது 102 அழைக்கவும்",
    },
  },
  te: {
    common: {
      home: "హోమ్",
      profile: "ప్రొఫైల్",
      student: "విద్యార్థి",
      everyone: "అందరికీ",
      cancel: "రద్దు",
      close: "మూసివేయి",
      or: "లేదా",
    },
    login: {
      welcome: "Mediverse కి స్వాగతం",
      subtitle: "AI ఆరోగ్య సహచరుడు",
      selectRole: "పాత్రను ఎంచుకోండి",
      student: "విద్యార్థి",
      everyone: "అందరికీ",
      forStudents: "విద్యార్థులకు",
      forEveryone: "అందరికీ",
      getStarted: "ప్రారంభించు",
      emergencyNote: "అత్యవసర పరిస్థితిలో డయల్ చేయండి",
      studentFeature1: "3D వైద్య శిక్షణ",
      studentFeature2: "దశల వారీ మార్గదర్శకత్వం",
      studentFeature3: "AR సిమ్యులేషన్",
      studentFeature4: "పురోగతిని ట్రాక్ చేయండి",
      everyoneFeature1: "పరికరాలను స్కాన్ చేయండి",
      everyoneFeature2: "రీడింగ్‌లను అర్థం చేసుకోండి",
      everyoneFeature3: "ఆసుపత్రులను కనుగొనండి",
      everyoneFeature4: "అత్యవసర సహాయం",
    },
    arScan: {
      medicalTraining: "వైద్య శిక్షణ",
      healthCompanion: "ఆరోగ్య సహచరుడు",
      studentTitle: "పరికర శిక్షకుడు",
      civilianTitle: "పరికరాన్ని స్కాన్ చేయండి",
      scanDevice: "పరికరాన్ని స్కాన్ చేయండి",
      quickAccess: "త్వరిత ప్రాప్యత",
      learnDevices: "పరికరాలను నేర్చుకోండి",
      allDevices: "అన్ని పరికరాలు",
      learn: "నేర్చుకో",
      viewGuide: "గైడ్ చూడండి",
      audio: "ఆడియో",
      back: "వెనుకకు",
      previous: "మునుపటి",
      next: "తదుపరి",
      complete: "పూర్తయింది",
      replayAudio: "ఆడియో మళ్ళీ",
      audioLanguage: "ఆడియో భాష",
    },
    manualInput: {
      title: "రీడింగ్ నమోదు చేయండి",
      enterReading: "రీడింగ్ నమోదు చేయండి",
      selectDevice: "పరికరాన్ని ఎంచుకోండి",
      bpMonitor: "రక్తపోటు",
      glucometer: "గ్లూకోమీటర్",
      thermometer: "థర్మామీటర్",
      oximeter: "ఆక్సిమీటర్",
      analyze: "విశ్లేషించు",
      enterValidReading: "చెల్లుబాటు అయ్యే రీడింగ్ నమోదు చేయండి",
    },
    categories: {
      normal: "సాధారణ",
      elevated: "పెరిగింది",
      risk: "ప్రమాదం",
      highRisk: "అధిక ప్రమాదం",
      emergency: "అత్యవసరం",
    },
    emergency: {
      title: "అత్యవసర సహాయం",
      emergency: "అత్యవసరం",
      findingHospitals: "ఆసుపత్రులను కనుగొంటోంది...",
      call: "కాల్",
      directions: "దిశలు",
      callNow: "ఇప్పుడు కాల్ చేయండి",
      call108: "108 కు కాల్ చేయండి",
      call102: "102 కు కాల్ చేయండి",
    },
    hospitalFinder: {
      title: "సమీపంలోని ఆసుపత్రులు",
      findHospital: "ఆసుపత్రిని కనుగొనండి",
    },
    contact: {
      title: "మమ్మల్ని సంప్రదించండి",
      subtitle: "సహాయం చేయడానికి మేము ఇక్కడ ఉన్నాము",
      email: "ఇమెయిల్",
      phone: "ఫోన్",
      send: "పంపు",
      emergencyNote: "అత్యవసర పరిస్థితికి 108 లేదా 102 కు కాల్ చేయండి",
    },
  },
  bn: {
    common: {
      home: "হোম",
      profile: "প্রোফাইল",
      student: "ছাত্র",
      everyone: "সবার জন্য",
      cancel: "বাতিল",
      close: "বন্ধ",
      or: "অথবা",
    },
    login: {
      welcome: "Mediverse-এ স্বাগতম",
      subtitle: "AI স্বাস্থ্য সহায়ক",
      selectRole: "ভূমিকা নির্বাচন করুন",
      student: "ছাত্র",
      everyone: "সবার জন্য",
      forStudents: "ছাত্রদের জন্য",
      forEveryone: "সবার জন্য",
      getStarted: "শুরু করুন",
      emergencyNote: "জরুরি অবস্থায় ডায়াল করুন",
      studentFeature1: "3D মেডিকেল ট্রেনিং",
      studentFeature2: "ধাপে ধাপে গাইডেন্স",
      studentFeature3: "AR সিমুলেশন",
      studentFeature4: "অগ্রগতি ট্র্যাক করুন",
      everyoneFeature1: "যন্ত্র স্ক্যান করুন",
      everyoneFeature2: "রিডিং বুঝুন",
      everyoneFeature3: "হাসপাতাল খুঁজুন",
      everyoneFeature4: "জরুরি সহায়তা",
    },
    arScan: {
      medicalTraining: "মেডিকেল ট্রেনিং",
      healthCompanion: "স্বাস্থ্য সহায়ক",
      studentTitle: "যন্ত্র প্রশিক্ষক",
      civilianTitle: "যন্ত্র স্ক্যান করুন",
      scanDevice: "যন্ত্র স্ক্যান করুন",
      quickAccess: "দ্রুত অ্যাক্সেস",
      learnDevices: "যন্ত্র শিখুন",
      allDevices: "সমস্ত যন্ত্র",
      learn: "শিখুন",
      viewGuide: "গাইড দেখুন",
      audio: "অডিও",
      back: "পেছনে",
      previous: "আগের",
      next: "পরবর্তী",
      complete: "সম্পূর্ণ",
      replayAudio: "অডিও আবার",
      audioLanguage: "অডিও ভাষা",
    },
    manualInput: {
      title: "রিডিং প্রবেশ করুন",
      enterReading: "রিডিং প্রবেশ করুন",
      selectDevice: "যন্ত্র নির্বাচন করুন",
      bpMonitor: "রক্তচাপ",
      glucometer: "গ্লুকোমিটার",
      thermometer: "থার্মোমিটার",
      oximeter: "অক্সিমিটার",
      analyze: "বিশ্লেষণ করুন",
      enterValidReading: "বৈধ রিডিং প্রবেশ করুন",
    },
    categories: {
      normal: "স্বাভাবিক",
      elevated: "বেড়েছে",
      risk: "ঝুঁকিতে",
      highRisk: "উচ্চ ঝুঁকি",
      emergency: "জরুরি",
    },
    emergency: {
      title: "জরুরি সহায়তা",
      emergency: "জরুরি",
      findingHospitals: "হাসপাতাল খুঁজছে...",
      call: "কল",
      directions: "দিকনির্দেশ",
      callNow: "এখনই কল করুন",
      call108: "108 কল করুন",
      call102: "102 কল করুন",
    },
    hospitalFinder: {
      title: "কাছাকাছি হাসপাতাল",
      findHospital: "হাসপাতাল খুঁজুন",
    },
    contact: {
      title: "যোগাযোগ করুন",
      subtitle: "সাহায্য করতে আমরা এখানে আছি",
      email: "ইমেইল",
      phone: "ফোন",
      send: "পাঠান",
      emergencyNote: "জরুরি অবস্থার জন্য 108 বা 102 এ কল করুন",
    },
  },
};

const voiceLanguages = {
  en: "en-US",
  hi: "hi-IN",
  mr: "mr-IN",
  ta: "ta-IN",
  te: "te-IN",
  bn: "bn-IN",
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem("mediverse_language");
    return saved || "en";
  });

  const setLanguage = useCallback((lang) => {
    setLanguageState(lang);
    localStorage.setItem("mediverse_language", lang);
  }, []);

  const t = useMemo(() => {
    const currentTranslations = translations[language] || translations.en;
    const englishTranslations = translations.en;
    const mergedTranslations = {};
    Object.keys(englishTranslations).forEach((category) => {
      if (typeof englishTranslations[category] === "object") {
        mergedTranslations[category] = {
          ...englishTranslations[category],
          ...(currentTranslations[category] || {}),
        };
      } else {
        mergedTranslations[category] =
          currentTranslations[category] || englishTranslations[category];
      }
    });
    return mergedTranslations;
  }, [language]);

  const getVoiceLang = useCallback(() => {
    return voiceLanguages[language] || "en-US";
  }, [language]);

  const speak = useCallback(
    (text, rate = 0.9) => {
      window.speechSynthesis.cancel();
      const utterance = new SpeechSynthesisUtterance(text);
      utterance.lang = voiceLanguages[language] || "en-US";
      utterance.rate = rate;
      window.speechSynthesis.speak(utterance);
    },
    [language],
  );

  const availableLanguages = [
    { code: "en", name: "English", nativeName: "English" },
    { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
    { code: "mr", name: "Marathi", nativeName: "मराठी" },
    { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
    { code: "te", name: "Telugu", nativeName: "తెలుగు" },
    { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  ];

  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t,
        getVoiceLang,
        speak,
        availableLanguages,
        voiceLanguages,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

export default LanguageContext;
